# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: ${file(./local.yml):organisation}
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: todo-api
# "service" is the name of this project. This will also be added to your AWS resource names.
service: todo-api

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  deploymentMethod: direct
  iam:
    role: ${file(./local.yml):iamRole}

build: 
  esbuild:
    minify: true
  

functions:
  GetTasks:
    handler: functions/GetTasks/index.handler
    events:
      - httpApi:
          path: /tasks
          method: get
  GetTask:
    handler: functions/GetTask/index.handler
    events:
      - httpApi:
          path: /tasks/{sk}
          method: get        
  PostTask:
    handler: functions/PostTask/index.handler
    events:
      - httpApi:
          path: /tasks
          method: post
  PutTask:
    handler: functions/PutTask/index.handler
    events:
      - httpApi:
          path: /tasks/{sk}
          method: put
  DeleteTask:
    handler: functions/DeleteTask/index.handler
    events:
      - httpApi:
          path: /tasks/{sk}
          method: delete
resources:
  Resources:
    EventTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: 'todo-db'
        AttributeDefinitions:
          - AttributeName: 'pk'
            AttributeType: 'S'
          - AttributeName: 'sk'
            AttributeType: 'S'
        KeySchema:
          - AttributeName: 'pk'
            KeyType: HASH
          - AttributeName: 'sk'
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST